import React from 'react';
// Assets
import {
  GithubIcon,
  BabelIcon,
  CssIcon,
  EjsIcon,
  ExpressIcon,
  HtmlIcon,
  JavascriptIcon,
  JssIcon,
  MaterialUiIcon,
  MongoIcon,
  NextJsIcon,
  NodeJsIcon,
  NoneIcon,
  NpmIcon,
  PhotoshopIcon,
  PythonIcon,
  ReactIcon,
  StyledComponentsIcon,
  WebpackIcon,
} from '../static/icons/technologies/index';

export default {
  github: { label: 'Github', icon: <GithubIcon /> },
  babel: { label: 'Babel', icon: <BabelIcon /> },
  css: { label: 'Babel', icon: <CssIcon /> },
  ejs: { label: 'EJS', icon: <EjsIcon /> },
  express: { label: 'Express', icon: <ExpressIcon /> },
  html: { label: 'HTML', icon: <HtmlIcon /> },
  javascript: { label: 'Javascript', icon: <JavascriptIcon /> },
  jss: { label: 'JSS', icon: <JssIcon /> },
  materialUi: { label: 'Material UI', icon: <MaterialUiIcon /> },
  monogDB: { label: 'MongoDB', icon: <MongoIcon /> },
  nextJs: { label: 'NextJs', icon: <NextJsIcon /> },
  nodeJs: { label: 'NodeJs', icon: <NodeJsIcon /> },
  none: { label: 'None', icon: <NoneIcon /> },
  npm: { label: 'NPM', icon: <NpmIcon /> },
  photoshop: { label: 'Photoshop', icon: <PhotoshopIcon /> },
  figma: { label: 'Figma', icon: '' },
  python: { label: 'Python', icon: <PythonIcon /> },
  react: { label: 'React', icon: <ReactIcon /> },
  styledComponents: { label: 'Styled Components', icon: <StyledComponentsIcon /> },
  webpack: { label: 'Webpack', icon: <WebpackIcon /> },
};
